version: '3'

tasks:
  backend:
    desc: Jalankan server backend dengan port 3000
    cmds:
      - go run ./cmd/server

  frontend:
    dir: ./web
    desc: Jalankan server frontend dengan port 8000
    cmds:
      - python -m http.server 8000

  dev:
    desc: Jalankan server backend dan frontend
    deps:
      - backend
      - frontend
